name: Deploy Python project to Azure Function App

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:

env:
  AZURE_FUNCTIONAPP_NAME: ProductEcho # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'   # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.8'                 # set this to the python version to use (supports 3.6, 3.7, 3.8)

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: "dc891217-e2e8-49f7-ac09-1158a9520ace"
          tenant-id: "83370987-42ca-46b6-88bd-671273dca361"
          subscription-id: "0b98d395-76e0-4bf0-a5fb-2529850f846c"

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
